# Copyright 2015 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
---
- name: Create required directories
  become: true
  file:
    group: "{{ zuul_user_group }}"
    owner: "{{ zuul_user_name }}"
    path: "{{ item }}"
    state: directory
  with_items:
    - /etc/zuul
    - /etc/zuul/ssl
    - /var/log/zuul

- name: Install gearman logging file
  become: true
  template:
    dest: "{{ zuul_file_gearman_logging_conf_dest }}"
    group: "{{ zuul_file_gearman_logging_conf_group }}"
    mode: "{{ zuul_file_gearman_logging_conf_mode }}"
    owner: "{{ zuul_file_gearman_logging_conf_owner }}"
    src: "{{ zuul_file_gearman_logging_conf_src }}"
  register: zuul_file_gearman_logging_conf
  notify: Reload zuul-scheduler
  when: zuul_file_gearman_logging_conf_manage

- name: Install executor logging file
  become: true
  template:
    dest: "{{ zuul_file_executor_logging_conf_dest }}"
    group: "{{ zuul_file_executor_logging_conf_group }}"
    mode: "{{ zuul_file_executor_logging_conf_mode }}"
    owner: "{{ zuul_file_executor_logging_conf_owner }}"
    src: "{{ zuul_file_executor_logging_conf_src }}"
  register: zuul_file_executor_logging_conf
  when: zuul_file_executor_logging_conf_manage

- name: Install fingergw logging file
  become: true
  template:
    dest: "{{ zuul_file_fingergw_logging_conf_dest }}"
    group: "{{ zuul_file_fingergw_logging_conf_group }}"
    mode: "{{ zuul_file_fingergw_logging_conf_mode }}"
    owner: "{{ zuul_file_fingergw_logging_conf_owner }}"
    src: "{{ zuul_file_fingergw_logging_conf_src }}"
  register: zuul_file_fingergw_logging_conf
  when: zuul_file_fingergw_logging_conf_manage

- name: Install merger logging file
  become: true
  template:
    dest: "{{ zuul_file_merger_logging_conf_dest }}"
    group: "{{ zuul_file_merger_logging_conf_group }}"
    mode: "{{ zuul_file_merger_logging_conf_mode }}"
    owner: "{{ zuul_file_merger_logging_conf_owner }}"
    src: "{{ zuul_file_merger_logging_conf_src }}"
  register: zuul_file_merger_logging_conf
  when: zuul_file_merger_logging_conf_manage

- name: Install scheduler logging file
  become: true
  template:
    dest: "{{ zuul_file_scheduler_logging_conf_dest }}"
    group: "{{ zuul_file_scheduler_logging_conf_group }}"
    mode: "{{ zuul_file_scheduler_logging_conf_mode }}"
    owner: "{{ zuul_file_scheduler_logging_conf_owner }}"
    src: "{{ zuul_file_scheduler_logging_conf_src }}"
  register: zuul_file_scheduler_logging_conf
  notify: Reload zuul-scheduler
  when: zuul_file_scheduler_logging_conf_manage

- name: Install zuul gearman ssl ca configuration
  become: true
  template:
    dest: "{{ zuul_file_gearman_ssl_ca_dest }}"
    group: "{{ zuul_file_gearman_ssl_ca_group }}"
    mode: "{{ zuul_file_gearman_ssl_ca_mode }}"
    owner: "{{ zuul_file_gearman_ssl_ca_owner }}"
    src: "{{ zuul_file_gearman_ssl_ca_src }}"
  register: zuul_file_gearman_ssl_ca

- name: Install zuul gearman ssl cert configuration
  become: true
  template:
    dest: "{{ zuul_file_gearman_ssl_cert_dest }}"
    group: "{{ zuul_file_gearman_ssl_cert_group }}"
    mode: "{{ zuul_file_gearman_ssl_cert_mode }}"
    owner: "{{ zuul_file_gearman_ssl_cert_owner }}"
    src: "{{ zuul_file_gearman_ssl_cert_src }}"
  register: zuul_file_gearman_ssl_cert

- name: Install zuul gearman ssl key configuration
  become: true
  template:
    dest: "{{ zuul_file_gearman_ssl_key_dest }}"
    group: "{{ zuul_file_gearman_ssl_key_group }}"
    mode: "{{ zuul_file_gearman_ssl_key_mode }}"
    owner: "{{ zuul_file_gearman_ssl_key_owner }}"
    src: "{{ zuul_file_gearman_ssl_key_src }}"
  register: zuul_file_gearman_ssl_key

- name: Install web logging file
  become: true
  template:
    dest: "{{ zuul_file_web_logging_conf_dest }}"
    group: "{{ zuul_file_web_logging_conf_group }}"
    mode: "{{ zuul_file_web_logging_conf_mode }}"
    owner: "{{ zuul_file_web_logging_conf_owner }}"
    src: "{{ zuul_file_web_logging_conf_src }}"
  register: zuul_file_web_logging_conf
  when: zuul_file_web_logging_conf_manage

- name: Install zuul main.yaml configuration
  become: true
  template:
    dest: "{{ zuul_file_main_yaml_dest }}"
    group: "{{ zuul_file_main_yaml_group }}"
    mode: "{{ zuul_file_main_yaml_mode }}"
    owner: "{{ zuul_file_main_yaml_owner }}"
    src: "{{ zuul_file_main_yaml_src }}"
  register: zuul_file_main_yaml
  notify:
    - Reload zuul-scheduler
  when: zuul_file_main_yaml_manage

- name: Install zuul configuration
  become: true
  template:
    dest: "{{ zuul_file_zuul_conf_dest }}"
    group: "{{ zuul_file_zuul_conf_group }}"
    mode: "{{ zuul_file_zuul_conf_mode }}"
    owner: "{{ zuul_file_zuul_conf_owner }}"
    src: "{{ zuul_file_zuul_conf_src }}"
  register: zuul_file_zuul_conf
