# Copyright 2015 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
---
- name: Define zuul_file_zuul_launcher_service_dest.
  set_fact:
    zuul_file_zuul_launcher_service_dest: "{{ __zuul_file_zuul_launcher_service_dest }}"
  when: zuul_file_zuul_launcher_service_dest is not defined

- name: Define zuul_file_zuul_launcher_service_mode.
  set_fact:
    zuul_file_zuul_launcher_service_mode: "{{ __zuul_file_zuul_launcher_service_mode }}"
  when: zuul_file_zuul_launcher_service_mode is not defined

- name: Define zuul_file_zuul_launcher_service_src.
  set_fact:
    zuul_file_zuul_launcher_service_src: "{{ __zuul_file_zuul_launcher_service_src }}"
  when: zuul_file_zuul_launcher_service_src is not defined

- name: Define zuul_file_zuul_launcher_service_config_dest.
  set_fact:
    zuul_file_zuul_launcher_service_config_dest: "{{ __zuul_file_zuul_launcher_service_config_dest }}"
  when: zuul_file_zuul_launcher_service_config_dest is not defined

- name: Define zuul_file_zuul_launcher_service_config_mode.
  set_fact:
    zuul_file_zuul_launcher_service_config_mode: "{{ __zuul_file_zuul_launcher_service_config_mode }}"
  when: zuul_file_zuul_launcher_service_config_mode is not defined

- name: Define zuul_file_zuul_launcher_service_config_src.
  set_fact:
    zuul_file_zuul_launcher_service_config_src: "{{ __zuul_file_zuul_launcher_service_config_src }}"
  when: zuul_file_zuul_launcher_service_config_src is not defined

- name: Define zuul_file_zuul_merger_service_dest.
  set_fact:
    zuul_file_zuul_merger_service_dest: "{{ __zuul_file_zuul_merger_service_dest }}"
  when: zuul_file_zuul_merger_service_dest is not defined

- name: Define zuul_file_zuul_merger_service_mode.
  set_fact:
    zuul_file_zuul_merger_service_mode: "{{ __zuul_file_zuul_merger_service_mode }}"
  when: zuul_file_zuul_merger_service_mode is not defined

- name: Define zuul_file_zuul_merger_service_src.
  set_fact:
    zuul_file_zuul_merger_service_src: "{{ __zuul_file_zuul_merger_service_src }}"
  when: zuul_file_zuul_merger_service_src is not defined

- name: Define zuul_file_zuul_merger_service_config_dest.
  set_fact:
    zuul_file_zuul_merger_service_config_dest: "{{ __zuul_file_zuul_merger_service_config_dest }}"
  when: zuul_file_zuul_merger_service_config_dest is not defined

- name: Define zuul_file_zuul_merger_service_config_mode.
  set_fact:
    zuul_file_zuul_merger_service_config_mode: "{{ __zuul_file_zuul_merger_service_config_mode }}"
  when: zuul_file_zuul_merger_service_config_mode is not defined

- name: Define zuul_file_zuul_merger_service_config_src.
  set_fact:
    zuul_file_zuul_merger_service_config_src: "{{ __zuul_file_zuul_merger_service_config_src }}"
  when: zuul_file_zuul_merger_service_config_src is not defined

- name: Define zuul_file_zuul_server_service_dest.
  set_fact:
    zuul_file_zuul_server_service_dest: "{{ __zuul_file_zuul_server_service_dest }}"
  when: zuul_file_zuul_server_service_dest is not defined

- name: Define zuul_file_zuul_server_service_mode.
  set_fact:
    zuul_file_zuul_server_service_mode: "{{ __zuul_file_zuul_server_service_mode }}"
  when: zuul_file_zuul_server_service_mode is not defined

- name: Define zuul_file_zuul_server_service_src.
  set_fact:
    zuul_file_zuul_server_service_src: "{{ __zuul_file_zuul_server_service_src }}"
  when: zuul_file_zuul_server_service_src is not defined

- name: Define zuul_file_zuul_server_service_config_dest.
  set_fact:
    zuul_file_zuul_server_service_config_dest: "{{ __zuul_file_zuul_server_service_config_dest }}"
  when: zuul_file_zuul_server_service_config_dest is not defined

- name: Define zuul_file_zuul_server_service_config_mode.
  set_fact:
    zuul_file_zuul_server_service_config_mode: "{{ __zuul_file_zuul_server_service_config_mode }}"
  when: zuul_file_zuul_server_service_config_mode is not defined

- name: Define zuul_file_zuul_server_service_config_src.
  set_fact:
    zuul_file_zuul_server_service_config_src: "{{ __zuul_file_zuul_server_service_config_src }}"
  when: zuul_file_zuul_server_service_config_src is not defined

- name: Copy zuul-launcher service into place.
  become: yes
  copy:
    dest: "{{ zuul_file_zuul_launcher_service_dest }}"
    group: "{{ zuul_file_zuul_launcher_service_group }}"
    mode: "{{ zuul_file_zuul_launcher_service_mode }}"
    owner: "{{ zuul_file_zuul_launcher_service_owner }}"
    src: "{{ zuul_file_zuul_launcher_service_src }}"

- name: Copy zuul-launcher service config into place.
  become: yes
  copy:
    dest: "{{ zuul_file_zuul_launcher_service_config_dest }}"
    group: "{{ zuul_file_zuul_launcer_service_config_group }}"
    mode: "{{ zuul_file_zuul_launcher_service_config_mode }}"
    owner: "{{ zuul_file_zuul_launcher_service_config_owner }}"
    src: "{{ zuul_file_zuul_launcher_service_config_src }}"

- name: Copy zuul-merger service into place.
  become: yes
  copy:
    dest: "{{ zuul_file_zuul_merger_service_dest }}"
    group: "{{ zuul_file_zuul_merger_service_group }}"
    mode: "{{ zuul_file_zuul_merger_service_mode }}"
    owner: "{{ zuul_file_zuul_merger_service_owner }}"
    src: "{{ zuul_file_zuul_merger_service_src }}"

- name: Copy zuul-merger service config into place.
  become: yes
  copy:
    dest: "{{ zuul_file_zuul_merger_service_config_dest }}"
    group: "{{ zuul_file_zuul_merger_service_config_group }}"
    mode: "{{ zuul_file_zuul_merger_service_config_mode }}"
    owner: "{{ zuul_file_zuul_merger_service_config_owner }}"
    src: "{{ zuul_file_zuul_merger_service_config_src }}"

- name: Copy zuul-server service into place.
  become: yes
  copy:
    dest: "{{ zuul_file_zuul_server_service_dest }}"
    group: "{{ zuul_file_zuul_server_service_group }}"
    mode: "{{ zuul_file_zuul_server_service_mode }}"
    owner: "{{ zuul_file_zuul_server_service_owner }}"
    src: "{{ zuul_file_zuul_server_service_src }}"

- name: Copy zuul-server service config into place.
  become: yes
  copy:
    dest: "{{ zuul_file_zuul_server_service_config_dest }}"
    group: "{{ zuul_file_zuul_server_service_config_group }}"
    mode: "{{ zuul_file_zuul_server_service_config_mode }}"
    owner: "{{ zuul_file_zuul_server_service_config_owner }}"
    src: "{{ zuul_file_zuul_server_service_config_src }}"

- name: Enable zuul-launcher service.
  become: yes
  service:
    enabled: "{{ zuul_service_zuul_launcher_enabled }}"
    name: "{{ zuul_service_zuul_launcher_name }}"
    state: "{{ zuul_service_zuul_launcher_state }}"
  register: __zuul_launcher_service
  when: zuul_service_zuul_launcher_manage

- name: Enable zuul-merger service.
  become: yes
  service:
    enabled: "{{ zuul_service_zuul_merger_enabled }}"
    name: "{{ zuul_service_zuul_merger_name }}"
    state: "{{ zuul_service_zuul_merger_state }}"
  register: __zuul_merger_service
  when: zuul_service_zuul_merger_manage

- name: Enable zuul-server service.
  become: yes
  service:
    enabled: "{{ zuul_service_zuul_server_enabled }}"
    name: "{{ zuul_service_zuul_server_name }}"
    state: "{{ zuul_service_zuul_server_state }}"
  register: __zuul_server_service
  when: zuul_service_zuul_server_manage
