# Copyright 2015 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
---
- name: Copy systemd file into place for zuul-merger.
  copy:
    dest: /etc/systemd/system
    src: ../../files/zuul-merger.service

- name: Copy systemd file into place for zuul-server.
  copy:
    dest: /etc/systemd/system
    src: ../../files/zuul-server.service

- name: Copy sysconfig file into place.
  copy:
    dest: /etc/sysconfig/zuul
    src: ../../files/zuul.sysconfig

- name: Enable zuul-merger service.
  service:
    enabled: yes
    name: zuul-merger
    state: started

- name: Enable zuul-server service.
  service:
    enabled: yes
    name: zuul-server
    state: started
